### ISSUE TITLE
Roadmap Speakerinnen

### ISSUE THREAD

**Issue by zaziemo** [rubymonsters/speakerinnen_liste#174]
Why this?

This task list creates an overview over the open issues and steps that are **(1) necessary to launch in beta**, **(2) to be done/completed for the first update** or **(3) nice to have** 

_1. necessary to launch in beta_
- [x] #167 clean up mess in error messages
- [x] #124 Flash messages show up at the top of the screen but our view stays in the center
- [x] #160 error messages on sign up page
- [x] #161 german translation
- [x] #170 Please translate two new German email messages
- [x] #166 Translations missing
- [x] #176 Translation "edit password"
- [x] #141 Signing up form asks for password on staging
- [x] #155 After login there is exception for the missing :host parameter
- [x] #172 click test
- [x] #168 improve user flow after confirmation
- [ ] #154 write blog post for describing the project
- [x] #146 Sign up with twitter: confusing error message
- [x] #177 styling: sign up form
- [x] #187 broken: Sign up with twitter
- [x] #183 search function in Speakerinnen
- [x] #182 confirm function for admin
- [x] #181 media links as model
- [x] #180 about page
- [x] #179 add the copyright warning to the profilepics
- [x] #186 add the website input field
- [x] #190 translations into english needed

_2. later_
- [x] #119 Admin Profiles cannot see their own profiles
- [ ] #112 Footer Sign up page
- [ ] #159 fix test
- [x] #185 Picture upload doesn't work properly
- [ ] add tests for the admin unpublish and publish method
- [x] #178 function: profiles edit > drag & drop of tags
- [x] #188 styling sign in/sign up button
- [ ] #189 replace Webrick for performance reasons

_3. nice to have_
- [x] #171 unification of usage/structure of translation scopes
- [x] #175 rename app/views/dashboard
- [ ] #184 CSS improvement
