### ISSUE TITLE
[FE] UI Framework Refactoring inuitcss –> Bootstrap

### ISSUE THREAD

**Issue by 1000miles** [rubymonsters/speakerinnen_liste#674]
# Context

At the moment [inuitcss](https://github.com/inuitcss/inuitcss) is being used as the frontend framework. While this tool seems to be a great tool for an out-of-the-box solution it has some disadvantages. 

- it requires a lot of documentation to understand what all the declared variables, elements, modules, etc. do which is not easy to find when needed
- it makes the css framework less accessible to coding beginners and new contributors because they would need to do a lot of research before they can start

Because `Bootstrap` seems to be the framework most people are familiar with we want to refactor the current code base and switch back to `Bootstrap`.

This ticket is the roadmap to identify and list all requirements and steps that are needed to refactor the code successfully. 

# Goals

Re-implement the Bootstrap framework without changing the overall functions and style, if possible.

# Notes 

tba

# Roadmap

- [ ] Identify all inuit css elements that currently implemented and used and replace them with Bootstrap elements if possible 
   - https://github.com/rubymonsters/speakerinnen_liste/tree/master/app/assets/stylesheets
   - https://github.com/rubymonsters/speakerinnen_liste/tree/master/app/assets/stylesheets/inuit
- [ ] Identify inuit css elements that are unused and remove them
- [ ] Check if additional/external packages/libraries/plugins are needed if Bootstrap doesn't provide a required function/element
- [ ] Write or refactor test cases to cover the most important features
- [ ] Document the refactoring

**Comment by tyranja** [comment]
Sounds great! :heart: Thank you!

**Comment by tyranja** [comment]
https://getbootstrap.com/docs/4.1/layout/overview/
https://fontawesome.com/icons?d=gallery&s=solid
https://github.com/twbs/bootstrap-rubygem

**Comment by tyranja** [comment]
http://shouldiuseacarousel.com/

**Comment by tyranja** [comment]
Styleguide:

for headlines:    `<h1 class="display-4">FAQ/How-to</h1>`
for smaller headlines:     `<h4 class="pt-4">Why is there no speaker for the topic I am looking for?</h4>`

**Comment by tyranja** [comment]
related issues:

 https://github.com/rubymonsters/speakerinnen_liste/issues/374
https://github.com/rubymonsters/speakerinnen_liste/issues/340

**Comment by tyranja** [comment]
Done!
