### ISSUE TITLE
Improve the admin interface

### ISSUE THREAD

**Issue by tyranja** [rubymonsters/speakerinnen_liste#749]
### Overview for admin improvements

_all tasks need to have an own issue and are linked here._

**profiles view**
- [x] (admin/profile/show) add comment to the profile view https://github.com/rubymonsters/speakerinnen_liste/issues/742
- [x] (admin/profile/index) show if a pic of the speaker is there https://github.com/rubymonsters/speakerinnen_liste/issues/747
- [x] add the profile.id to the table ( https://github.com/rubymonsters/speakerinnen_liste/issues/743 )
- [x] keep pagination after an action

**tags view**
- [x] (index/view) show the speaker/profile that are using the tag ( https://github.com/rubymonsters/speakerinnen_liste/issues/789 )
- [x] (admin/tags/index & (admin/tags/edit) make one form instead of separate actions for edit, language and category ( https://github.com/rubymonsters/speakerinnen_liste/issues/789 )
- [x] Add sort to the tags overview (https://github.com/rubymonsters/speakerinnen_liste/issues/789)
- [x] improve filters area (https://github.com/rubymonsters/speakerinnen_liste/issues/815)
- [x] keep pagination after an action
- [x] After an action on the edit page, go back to same tag on the tag overview  
- [x] Move notifications to `#top-anchor` location 
- [ ] Validate that tag has tagging

**category view**
- [ ] make checkboxes for categories' assignment https://github.com/rubymonsters/speakerinnen_liste/issues/633

**overview**
- [ ] the admin start page could use a better overview, like fiftypercent
![overview](https://user-images.githubusercontent.com/1218914/46152822-18076c00-c272-11e8-9e70-ab47139b07f4.png)

**Comment by netagonen** [comment]
Open question: when tag is merged with an existing tag, old tag remains. Is this the wanted behavior?

**Comment by zaziemo** [comment]
@netagonen no, the old tag should be deleted.

**Comment by netagonen** [comment]
@tyranja, @zaziemo 
1. Is the category view issue not relevant anymore? 
2. I am not sure how to improve the admin start page overview: what would be the user's needs in this case? 
3. Last idea for improvement: to have one navigation bar to all the admin area. now it"s bit of a mass. BUT also could be that admin don't need this. What do you think?

**Comment by netagonen** [comment]
tags view -  Validate that tag has tagging: in a different issue
categories view - make checkboxes for categories' assignment #633: not relevant anymore
overview - the admin start page could use a better overview, like fiftypercent: unnecessary
-->issue can be closed
